dist: bionic

os:
- windows

language: minimal

before_install:
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then 
    choco install shellcheck -y;
    git clone https://github.com/bats-core/bats-core.git;
    cd bats-core;
    bash ./install.sh $HOME;
    cd ..;
  fi
script: 
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then 
    export PATH="${PATH}:${HOME}/bin"
    mingw32-make travis; 
  fi
