dist: bionic

os:
- windows

language: minimal

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install bats shellcheck yq; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo snap install yq; fi
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install yq shellcheck; fi

script: 
- make travis
