dist: bionic

os:
- windows

language: minimal

script: 
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then 
    choco install shellcheck -y;
    git clone https://github.com/bats-core/bats-core.git;
    cd bats-core
    bash ./install.sh $HOME
    cd ..
    mingw32-make travis; 
  fi
