dist: bionic

os:
- linux
- osx

language: minimal

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 brew install bats shellcheck yq; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo snap install yq; fi

script: 
- make travis
