#!/bin/bash

test -n "${DEBUG}" && set -x
set -e

function fail() {
  test -n "${1}" && echo "${1}" && echo
  exit 2
}

function readValue() {
  printf "Please provide %s: " "${1}"
  read -r VALUE
  echo
  test -z "${VALUE}" && fail "Error: You must supply a value for $1"
  export "${2}=${VALUE}"
}

function readSecret() {
  printf "Please provide %s: " "${1}"
  read -s -r VALUE
  echo
  test -z "${VALUE}" && fail "Error: You must supply a value for $1"
  export "${2}=${VALUE}"
}

function ensureValue() {
  configName="BRANCHOUT_${2}"
  if test -z "${!configName}"; then
    readValue "${1}" "${configName}"
    "${BRANCHOUT_PATH}/branchout" set "${configName}" "${!configName}"
  fi
}

function ensureConfigValue() {
  configName="BRANCHOUT_CONFIG_${2}"
  if test -z "${!configName}"; then
    readValue "${1}" "${configName}"
    "${BRANCHOUT_PATH}/branchout" set-config "${2}" "${!configName}"
  fi
}

export BO_THEME_RESET="\\033[0m"
export BO_THEME_OK="\\033[0m"
export BO_THEME_NOTICE="\\033[35m"
export BO_THEME_ERROR="\\033[31m"
export BO_THEME_WARNING="\\033[38;5;202m"
export BO_THEME_HIGHLIGHT="\\033[38;5;11m"

BRANCHOUT_PROJECTS_DIRECTORY=projects
# shellcheck source=examples/branchoutrc
test -f ~/.config/branchoutrc && source ~/.config/branchoutrc
export BRANCHOUT_PROJECTS_DIRECTORY
