#!/bin/bash

test -n "${DEBUG}" && set -x
set -e 

function runYarn() {
    HOME=${BRANCHOUT_HOME}/node 
    YARN_CACHE_FOLDER=${BRANCHOUT_HOME}/node/cache yarn --use-yarnrc "${BRANCHOUT_HOME}/node/yarnrc" "${@}"
}

function yarnSettings() {
    ensureValue "your npm registry" "NPM_REGISTRY"
    if [[ ${BRANCHOUT_NPM_REGISTRY} =~ ^http:// ]]; then
      export BRANCHOUT_NPM_REGISTRY="https:${BRANCHOUT_NPM_REGISTRY#*:}"
      "${BRANCHOUT_PATH}/branchout" set "NPM_REGISTRY" "https${BRANCHOUT_NPM_REGISTRY}"
    fi
    
    ensureConfigValue "npm registry username" "NPM_USER"
    readSecret "npm registry secret" "NPM_PASS"
    ensureConfigValue "npm registry email (git commit author)" "GIT_EMAIL"

    if test ! -d "${BRANCHOUT_HOME}/node/"; then
      echo "create the branchout directory for node ${BRANCHOUT_HOME}/node/"
      mkdir -p "${BRANCHOUT_HOME}/node/"
    fi
    
    echo "writing yarn config to ${BRANCHOUT_HOME}/node/yarnrc"
    if test -f "${BRANCHOUT_DIRECTORY}/branchout-templates/yarnrc"; then
        echo "using yarnrc template ${BRANCHOUT_DIRECTORY}/branchout-templates/yarnrc"
        echo <(cat "${BRANCHOUT_DIRECTORY}/branchout-templates/yarnrc") > "${BRANCHOUT_HOME}/node/yarnrc"
    else
        echo "registry ${BRANCHOUT_NPM_REGISTRY}
always-auth true
user ${BRANCHOUT_CONFIG_NPM_USER}
email ${BRANCHOUT_CONFIG_GIT_EMAIL}
disable-self-update-check true
" > "${BRANCHOUT_HOME}/node/yarnrc"
    fi

    echo "writing npm config to ${BRANCHOUT_HOME}/node/.npmrc"
    BASE_64_AUTH=$(echo -n "${BRANCHOUT_CONFIG_NPM_USER}:${NPM_PASS}" | base64)
    if test -f "${BRANCHOUT_DIRECTORY}/branchout-templates/.npmrc"; then
        echo "using npmrc template ${BRANCHOUT_DIRECTORY}/branchout-templates/npmrc"
        echo <(cat "${BRANCHOUT_DIRECTORY}/branchout-templates/.npmrc") > "${BRANCHOUT_HOME}/node/.npmrc"
    else
        echo "_auth=${BASE_64_AUTH}
always-auth=true" > "${BRANCHOUT_HOME}/node/.npmrc"
    fi
}

function usage() {
  echo "branchout-yarn settings|show|install|<package.json command>

  settings

      Generate .npmrc and yarnc for private repository access

  install

      Install the node modules declared in the package.json

  <package.json scripts>

      Run a script defined in the package.json e.g. clean, test, serve
  "

  exit 1
}

function main() {
  test $# -gt 0 || usage

  BRANCHOUT_PATH="$(dirname "$0")"

  # shellcheck source=branchout-configuration
  . "${BRANCHOUT_PATH}/branchout-configuration"
  # shellcheck source=branchout-environment
  . "${BRANCHOUT_PATH}/branchout-environment"

  case "${1}" in
    settings)
      yarnSettings "${*}"
      ;;
    show)
      grep -v auth "${BRANCHOUT_HOME}/node/yarnrc"
      ;;
    *)
      test -f "${BRANCHOUT_HOME}/node/.npmrc" || yarnSettings
      test -f "${BRANCHOUT_HOME}/node/yarnrc" || yarnSettings
      runYarn "${@}"
  esac
}

main "${@}"

