#!/bin/bash

function usage() {
  echo "branchout-project list|status|pull [project]
  
  status project-name
      
      Return the status of the given project, Not cloned, branch, rebasing
  
  pull project-name
  
      Attempt to pull the project, show the branch or error
  
  list [prefix]
  
      List all the projects with the given prefix
  
  "
  
  exit 1
}

function projectList() {
  if test $# -eq 0; then
    sort "${BRANCHOUT_DIRECTORY}/Branchoutprojects"
  else
    grep "^${1}" "${BRANCHOUT_DIRECTORY}/Branchoutprojects" | sort
  fi
}

function projectListWithGroups() {
  sort <(cat "${BRANCHOUT_DIRECTORY}/Branchoutprojects") <(branchout-project groups)
}

function projectStatus() {
   projectGroup=$(branchout-group derive "${1}")
   if test -d "${BRANCHOUT_DIRECTORY}/${projectGroup}/${1}"; then
     cd "${BRANCHOUT_DIRECTORY}/${projectGroup}/${1}" || usage "Failed to enter project directory"
     projectBranch=$(git rev-parse --abbrev-ref HEAD)
     if test "${projectBranch}" = "master"; then
       echo -e "\033[0m${2}${projectGroup}/${1}\033[70D\033[70C\033m${projectBranch}\033[0m"
     else
       echo -e "\033[0m${2}${projectGroup}/${1}\033[70D\033[70C\033[32m${projectBranch}\033[0m"
     fi
   else
     echo -e "\033[0m${2}${projectGroup}/${1}\033[70D\033[70C\033[35mNot cloned\033[0m"
   fi
}

function projectUpdate() {
  cd "${BRANCHOUT_DIRECTORY}/${projectGroup}/${1}" || usage "Failed to enter project directory"
  git pull --rebase origin > /dev/null 2>&1 || (echo -e "\033[0mFailed \033[31m${projectGroup}/${1}\033[0m \033[70D\033[70C\033[1m $( git pull --rebase origin 2>&1| head -n1)\033[0m")
}

function projectClone() {
  test -d "${projectGroup}" || branchout-group pull "${projectGroup}"
  cd "${projectGroup}" || useage "Project group ${projectGroup} directory not found"
  echo -e "\033[0mCloning \033[92m${projectGroup}/${1}\033[0m"
  RESULT=$(git clone "${BRANCHOUT_GIT_BASEURL}/${1}" 2>&1)
  if test $? -eq 0; then
    projectStatus "${1}" "Pulled "
  else
    echo -e "\033[0mCloning failed: \033[31m${projectGroup}/${1}\n${RESULT}\033[0m"
  fi
}

function projectPull() {
   projectGroup=$(branchout-group derive "${1}")
   if test -d "${BRANCHOUT_DIRECTORY}/${projectGroup}/${1}/.git"; then
     projectUpdate "${1}"
   else
     projectClone "${1}"
   fi
}

function main() {
  case "${1}" in
    list)
      if test "${2}" = "--grouped"; then
        projectListWithGroups
      else
        projectList "${2}"
      fi
      ;;
    status)
      test -n "${2}" || usage "Must provide project"
      projectStatus "${2}"
      ;;
    pull)
      test -n "${2}" || usage "Must provide project"
      projectPull "${2}"
      ;;
    *)
      usage
  esac
}

main "${@}"
