#!/bin/bash

function branchoutDirectory() {
  BRANCHOUT_DIRECTORY="${PWD}"
  while test ! -f "${BRANCHOUT_DIRECTORY}/.branchout"; do
    BRANCHOUT_DIRECTORY=$(dirname "${BRANCHOUT_DIRECTORY}")
    test "${BRANCHOUT_DIRECTORY}" = '/' && echo ".branchout configuration not found in parent hierarchy, run branchout init" && exit 1
  done
  export BRANCHOUT_DIRECTORY
}

function branchoutStatus() {
  branchoutDirectory
}


case "$1" in
  status)
    branchoutStatus
    ;;
  *)
    echo "branchout: a tool for managing multi-repo projects
    
    status: show the list of known projects and their current state
    "
    ;;
esac
