#!/bin/bash

test -n "${DEBUG}" && set -x
set -e

function fail() {
  test -n "${1}" && echo "${1}" && echo
  exit 2
}

function getConfigValue() {
  if test -f "${BRANCHOUT_HOME}/branchoutrc"; then
    grep "^BRANCHOUT_CONFIG_${1}=" "${BRANCHOUT_HOME}/branchoutrc" | sed -e 's,^.*="\(.*\)"$,\1,'
  fi
}

function setConfigValue() {
  test -z "${2}" && usage "You must supply a value to set"
  test -f "${BRANCHOUT_HOME}/branchoutrc" && grep -v "^BRANCHOUT_CONFIG_${1}=" "${BRANCHOUT_HOME}/branchoutrc" > "${BRANCHOUT_HOME}/branchoutrc.tmp" && true
  echo "BRANCHOUT_CONFIG_${1}=\"${2}\"" >> "${BRANCHOUT_HOME}/branchoutrc.tmp"
  sort "${BRANCHOUT_HOME}/branchoutrc.tmp" > "${BRANCHOUT_HOME}/branchoutrc"
  rm "${BRANCHOUT_HOME}/branchoutrc.tmp"
}

function getValue() {
  grep "^${1}=" "${BRANCHOUT_DIRECTORY}/${BRANCHOUT_FILE}" | sed -e 's,^.*="\(.*\)"$,\1,'
}

function setValue() {
  grep -v "^${1}=" "${BRANCHOUT_DIRECTORY}/${BRANCHOUT_FILE}" > "${BRANCHOUT_DIRECTORY}/${BRANCHOUT_FILE}".tmp && true
  echo "${1}=\"${2}\"" >> "${BRANCHOUT_DIRECTORY}/${BRANCHOUT_FILE}.tmp"
  sort "${BRANCHOUT_DIRECTORY}/${BRANCHOUT_FILE}.tmp" > "${BRANCHOUT_DIRECTORY}/${BRANCHOUT_FILE}"
  rm "${BRANCHOUT_DIRECTORY}/${BRANCHOUT_FILE}.tmp"
}

function readValue() {
  if test -z "${3}"; then
    printf "Please provide %s: " "${1}"
  else
    printf "Please provide %s [%s]: " "${1}" "${3}"
  fi
  read -r VALUE
  echo
  test -n "${3}" && VALUE="${3}"
  test -z "${VALUE}" && fail "Error: You must supply a value for $1"
  export "${2}=${VALUE}"
}

function readSecret() {
  printf "Please provide %s: " "${1}"
  read -s -r VALUE
  echo
  test -z "${VALUE}" && fail "Error: You must supply a value for $1"
  export "${2}=${VALUE}"
}

function ensureValue() {
  configName="BRANCHOUT_${2}"
  if test -z "${!configName}"; then
    readValue "${1}" "${configName}" "${3}"
    setValue "${configName}" "${!configName}"
  fi
}

function ensureConfigValue() {
  configName="BRANCHOUT_CONFIG_${2}"
  if test -z "${!configName}"; then
    readValue "${1}" "${configName}" "${3}"
    setConfigValue "${2}" "${!configName}"
  fi
}

export BO_THEME_RESET="\\033[0m"
export BO_THEME_OK="\\033[0m"
export BO_THEME_NOTICE="\\033[35m"
export BO_THEME_ERROR="\\033[31m"
export BO_THEME_WARNING="\\033[38;5;202m"
export BO_THEME_HIGHLIGHT="\\033[38;5;11m"

BRANCHOUT_PROJECTS_DIRECTORY=projects
# shellcheck source=examples/branchoutrc
test -f ~/.config/branchoutrc && source ~/.config/branchoutrc
export BRANCHOUT_PROJECTS_DIRECTORY
